apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:

        - name: r-shiny-server
          image: rocker/shiny
          ports:
            - name: http
              containerPort: 3838
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /srv
              name: shiny-app

        - name: git-sync
          image: openweb/git-sync:0.0.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /git
              name: shiny-app
          env:
          - name: GIT_SYNC_REPO
            value: ${CIRCLE_REPOSITORY_URL}
          - name: GIT_SYNC_REV
            value: ${CIRCLE_SHA1}
          - name: GIT_SYNC_ROOT
            value: /git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_WAIT
            value: "10"

      volumes:
        - name: shiny-app
          emptyDir: {}
