apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  sessionAffinity: ClientIP
  selector:
    app: ${APP_NAME}
  ports:
  - port: 80
    targetPort: 3838
